FROM openjdk:8-jre-alpine

RUN mkdir /app

WORKDIR /app

ADD $TRAVIS_BUILD_DIR/target/microservices-profile-api-2.5.0-SNAPSHOT.jar /app

EXPOSE 8085

CMD ["java", "-jar", "/app/microservices-profile-api-2.5.0-SNAPSHOT.jar"]
