kumuluzee:
  datasources:
    - jndi-name: jdbc/BooksDS
      connection-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      max-pool-size: 20
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                     <Configuration name="profiles">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                                <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                            </Console>
                             <Socket name="socket" host="0b624eb9-4830-45fa-bd94-6c828d54e71c-ls.logit.io" port="23073">
                                  <JsonLayout properties="true"/>
                                </Socket>
                        </Appenders>
                        <Loggers>
                            <!-- Default logger -->
                            <Root level="info">
                                <AppenderRef ref="console"/>
                                <AppenderRef ref="socket"/>
                             </Root>
                        </Loggers>
                    </Configuration>'
    loggers:
      - name: ''
        level: INFO
  config:
      start-retry-delay-ms: 500
      max-retry-delay-ms: 900000
      etcd:
        hosts: http://127.0.0.1:2379
