kumuluzee:
  datasources:
    - jndi-name: jdbc/BooksDS
      connection-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      max-pool-size: 20
  logs:
      config-file: '<?xml version="1.0" encoding="UTF-8"?>
                    <Configuration name="profiles">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                                <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                            </Console>
                            <!--<Socket name="logstash" host="4da2b37b-f061-42e4-bedf-fe629953cccf-ls.logit.io" port="15015" protocol="tcp">
                                <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                            </Socket>-->
                        </Appenders>
                        <Loggers>
                            <!-- Default logger -->
                            <Root level="all">
                                <AppenderRef ref="console" level="info"/>
                               <!-- <AppenderRef ref="logstash" level="trace"/>-->
                            </Root>
                        </Loggers>
                    </Configuration>'

  config:
      start-retry-delay-ms: 500
      max-retry-delay-ms: 900000
      etcd:
        hosts: http://127.0.0.1:2379

rest-properties:
  external-services:
    order-service:
      enabled: true